# Generated by Django 6.0.3 on 2026-04-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(default='Lattafa', max_length=100)),
                ('notes', models.CharField(help_text='e.g. Strawberry · Vanilla · Musk · 75ml', max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('badge', models.CharField(blank=True, help_text='e.g. Best Seller, New In', max_length=50)),
                ('accent', models.CharField(choices=[('ac-purple', 'Purple'), ('ac-gold', 'Gold'), ('ac-red', 'Red'), ('ac-pink', 'Pink'), ('ac-teal', 'Teal'), ('ac-brown', 'Brown'), ('ac-sunny', 'Yellow/Sunny'), ('ac-rose', 'Rose')], default='ac-gold', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number = shown first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
